version = 1

test_patterns = ["**/*_test.go"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/axetroy/watchdog"]

[[analyzers]]
name = "javascript"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true
