name: docker

on:
  push:
    branches:
      - "master"
    paths:
      - "**/*.go"
      - "**/go.mod"
      - "**/go.sum"
      - ".github/workflows/docker.yml"
      - ".github/workflows/build.yml"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: axetroy/watchdog:latest

      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash
        if: startsWith(github.ref, 'refs/tags/v')

      - name: Build and push to version
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: axetroy/watchdog:${{ steps.tag_name.outputs.current_version }}
        if: startsWith(github.ref, 'refs/tags/v')