name: ci

on:
  push:
    branches:
      - "main"
    paths:
      - "**/*.go"
      - "**/go.mod"
      - "**/go.sum"
      - ".github/workflows/docker.yml"
      - ".github/workflows/build.yml"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest

